#!/usr/bin/env python3
"""
This module provides a function to evaluate classifier performance
by creating a detailed textual classification report using Scikit-learn.
"""
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """
    Generates a detailed classification report mapping precision,
    recall, and F1-score for each evaluation class.
    Arguments:
        true_labels: Ground truth target labels.
        predicted_labels: Predicted labels returned by the model.
        class_names: List of strings corresponding to the label indices.
    Returns:
        A string containing the classification report generated by Scikit-learn
    """
    report = metrics.classification_report(
        true_labels, predicted_labels, target_names=list(class_names)
    )
    return report
