#!/usr/bin/env python3
"""Evaluate classifier performance using Scikit-learn."""
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """Generate a classification report with precision, recall, and F1.

    Args:
        true_labels: Ground truth target labels.
        predicted_labels: Predicted labels returned by the model.
        class_names: List of strings corresponding to the label indices.

    Returns:
        str: The classification report generated by Scikit-learn.
    """
    target_names = list(class_names) if class_names is not None else None
    report = metrics.classification_report(
        true_labels, predicted_labels, target_names=target_names
    )
    return report
